### ISSUE TITLE
Clear navigation stack after splash screen.

### ISSUE THREAD

**Issue by Grigoriym** [furkanaskin/Weatherapp#10]
I think being in dashboard fragment or in search fragment and pressing back button, it is strange to show splash screen again.

**Comment by Grigoriym** [comment]
Here the code:
```
    <fragment
        android:id="@+id/splashFragment"
        android:name="com.faskn.app.weatherapp.ui.splash.SplashFragment"
        android:label="SplashFragment">
        <action
            android:id="@+id/action_splashFragment_to_dashboardFragment"
            app:destination="@id/dashboardFragment"
            app:launchSingleTop="true"
            app:popUpTo="@+id/splashFragment"
            app:popUpToInclusive="true" />
        <action
            android:id="@+id/action_splashFragment_to_searchFragment"
            app:destination="@id/searchFragment"
            app:launchSingleTop="true"
            app:popUpTo="@+id/splashFragment"
            app:popUpToInclusive="true" />
    </fragment>
```

**Comment by furkanaskin** [comment]
@Grigoriym Thank you for enlightening me.  Why don't you open a pull request?

**Comment by Grigoriym** [comment]
@furkanaskin That is why I wrote the code here. I can't make a pull request.
![01](https://user-images.githubusercontent.com/31949421/74089681-da555d00-4acd-11ea-9ac0-21c70a996602.PNG)

**Comment by furkanaskin** [comment]
I think you are trying to push directly. First of all fork this repo and then perform your commit on fork. After that you can create a new pull request.

**Comment by furkanaskin** [comment]
Closed by @Grigoriym
